/// <reference types="vitest/globals" />

// Set required env vars BEFORE any source module imports.
// This prevents config.ts from calling process.exit(1)
// and db.ts from writing to the filesystem.
process.env.CHEF_API_KEY = 'test-api-key-12345'
process.env.GITHUB_TOKEN = 'ghp_test_token'
process.env.PORT = '0'
process.env.HOST = '127.0.0.1'
process.env.DOCKER_SOCKET = '/var/run/docker.sock'
process.env.SSH_HOSTS = 'dev:deploy@10.0.0.1:~/.ssh/id_rsa'
process.env.TODO_PATH = '/tmp/test-todo.md'
process.env.DB_PATH = ':memory:'
process.env.CRON_TIMEZONE = 'UTC'
process.env.WEBHOOK_SECRET = ''
process.env.NOTIFY_TELEGRAM_BOT_TOKEN = ''
process.env.NOTIFY_TELEGRAM_CHAT_ID = ''
process.env.NOTIFY_DISCORD_WEBHOOK_URL = ''
process.env.HOOK_EVENT_TTL_DAYS = '30'
process.env.LOG_SOURCES = ''
process.env.LOG_INDEX_INTERVAL_SECONDS = '300'
process.env.LOG_TAIL_DEFAULT_LINES = '100'
process.env.MONITORED_SERVICES = ''
process.env.IMAP_HOST = ''
process.env.IMAP_PORT = '993'
process.env.IMAP_USER = ''
process.env.IMAP_PASS = ''
process.env.IMAP_TLS = 'true'
process.env.EMAIL_CACHE_TTL_SECONDS = '300'
process.env.BW_SESSION = ''
process.env.BW_CLI_PATH = 'bw'
process.env.ANSIBLE_PLAYBOOK_DIR = ''
process.env.ANSIBLE_INVENTORY = ''
process.env.NEXTCLOUD_URL = 'https://test.example.com'
process.env.NEXTCLOUD_ADMIN_USER = 'admin'
process.env.NEXTCLOUD_ADMIN_PASSWORD = 'test-password'
process.env.NEXTCLOUD_TALK_ROOM_TOKEN = 'test-room-token'
process.env.NODE_ENV = 'test'
